### ISSUE TITLE
checklist of intra page links needed

### ISSUE THREAD

**Issue by mobb** [EDIorg/data-package-best-practices#33]
- [ ] from dataset to methods > datasource 
- [ ] from dataSource to dataset (with note that example shows only a few elements, you could add them all)
- [ ] from entity to constraint

**Comment by mobb** [comment]
grep "below", or "see below". these should be linked to the section.

**Comment by gremau** [comment]
Revising this issue a little bit. There are quite a few in-text references between chapters or sections that don't appear as hyperlinks. It would be good to make them hyperlinks. Someone would just need to reverence the relevant .qmd file and heading, i.e. `[Chapter 2](chapter_2.qmd)`.
